version: '3.1'

services:
  novnc:
    image: kpsimoulis/freenect
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=948
      - LD_PRELOAD=/usr/local/lib/fakenect/libfakenect.so
      - FAKENECT_PATH=/session
    volumes:
      - ./session:/session
    ports:
      - "6080:6081"