version: '3'

services:
  freenect:
    image: kpsimoulis/freenect
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=948
      - VNC_PASSWORD=${VNC_PASSWORD}
    volumes:
      - ./session:/session
    ports:
      - "6080:6081"
      - "5900:5900"